//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyMapApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirState()
        {
            this.Point = new HashSet<Point>();
        }
    
        public int Id { get; set; }
        public Nullable<double> CO2Value { get; set; }
        public Nullable<double> NO2Value { get; set; }
        public Nullable<double> Dust { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point> Point { get; set; }
    }
}
