//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyMapApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geosmile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Geosmile()
        {
            this.Point = new HashSet<Point>();
        }
    
        public int Id { get; set; }
        public Nullable<double> TemparatureMinValue { get; set; }
        public Nullable<double> TemparatureMaxValue { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public string Weather { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point> Point { get; set; }
    }
}
