//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyMapApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int Id { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AirStateId { get; set; }
        public Nullable<int> SoilStateId { get; set; }
        public Nullable<int> WaterStateId { get; set; }
        public Nullable<int> GeosmileId { get; set; }
    
        public virtual AirState AirState { get; set; }
        public virtual Geosmile Geosmile { get; set; }
        public virtual Region Region { get; set; }
        public virtual SoilState SoilState { get; set; }
        public virtual User User { get; set; }
        public virtual WaterState WaterState { get; set; }
    }
}
