//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologicalMapAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAction
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StationDataId { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTimeEvent { get; set; }
    
        public virtual StationData StationData { get; set; }
        public virtual User User { get; set; }
    }
}
