

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EcologicalMapAPI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EcologicalMapEntities : DbContext
{
    public EcologicalMapEntities()
        : base("name=EcologicalMapEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AirState> AirState { get; set; }

    public virtual DbSet<Geosmile> Geosmile { get; set; }

    public virtual DbSet<LogAction> LogAction { get; set; }

    public virtual DbSet<Station> Station { get; set; }

    public virtual DbSet<StationData> StationData { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserData> UserData { get; set; }

    public virtual DbSet<UserGeosmile> UserGeosmile { get; set; }

}

}

