//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologicalMapAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationData()
        {
            this.LogAction = new HashSet<LogAction>();
        }
    
        public int Id { get; set; }
        public int StationId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<double> COValue { get; set; }
        public Nullable<double> NO2Value { get; set; }
        public Nullable<double> NOValue { get; set; }
        public Nullable<double> PM10 { get; set; }
        public Nullable<double> PM25 { get; set; }
        public Nullable<double> TValue { get; set; }
        public Nullable<double> ModuleV { get; set; }
        public Nullable<double> V { get; set; }
        public Nullable<double> Pressure { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<double> Precipitation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogAction> LogAction { get; set; }
        public virtual Station Station { get; set; }
    }
}
