
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EcologicalMapAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StationData
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public StationData()
    {

        this.LogAction = new HashSet<LogAction>();

    }


    public int Id { get; set; }

    public int StationId { get; set; }

    public System.DateTime DateTime { get; set; }

    public Nullable<double> COValue { get; set; }

    public Nullable<double> NO2Value { get; set; }

    public Nullable<double> NOValue { get; set; }

    public Nullable<double> PM10 { get; set; }

    public Nullable<double> PM25 { get; set; }

    public Nullable<double> TValue { get; set; }

    public Nullable<double> ModuleV { get; set; }

    public Nullable<double> V { get; set; }

    public Nullable<double> Pressure { get; set; }

    public Nullable<double> Humidity { get; set; }

    public Nullable<double> Precipitation { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LogAction> LogAction { get; set; }

    public virtual Station Station { get; set; }

}

}
