//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologicalMapAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int GeosmileId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> AirStateId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<double> Temperature { get; set; }
    
        public virtual AirState AirState { get; set; }
        public virtual Geosmile Geosmile { get; set; }
        public virtual User User { get; set; }
    }
}
