
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EcologicalMapAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserData
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserData()
    {

        this.UserGeosmile = new HashSet<UserGeosmile>();

    }


    public int Id { get; set; }

    public int UserId { get; set; }

    public Nullable<double> Latitude { get; set; }

    public Nullable<double> Longitude { get; set; }

    public Nullable<int> AirStateId { get; set; }

    public System.DateTime DateTime { get; set; }

    public Nullable<double> Temperature { get; set; }



    public virtual AirState AirState { get; set; }

    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserGeosmile> UserGeosmile { get; set; }

}

}
